"""init tables

Revision ID: 989e1a4baa3d
Revises: 0fa9eb2d41ed
Create Date: 2025-11-24 08:39:56.176790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989e1a4baa3d'
down_revision: Union[str, Sequence[str], None] = '0fa9eb2d41ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_title_key'), 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tasks_title_key'), 'tasks', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
